---
- name: Install Jenkins software
  hosts: localhost
  become: yes
  vars: 
    ansible_become_pass: suntec123
  tasks:
  - name: Download jenkins repo
    shell:
      wget -o /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo &
 # - name: Import Jenkins CI key
    #get_url:
    #rpm_key:
      #state: present
      #key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key 
      #key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key &&
    #  dest: /opt
      #state: present
  - name: Install Jenkins
    package:
      name: “{{ item }}”
      state: latest
    with_items:
      - jenkins
  - name: Allow port 8080
    shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
  - name: Start the server
    service:
      name: jenkins
      state: started
  - wait_for:
    port: 8080
